; Waveshare ESP32-S3-Touch-AMOLED-2.06
; ESP32-S3R8: 16 MB QIO flash and 8 MB octal PSRAM.
[env:esp32-s3-touch-amoled-2-06]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-s3-devkitc1-n16r8
framework = espidf
board_build.partitions = partitions.csv
board_build.filesystem = spiffs
monitor_speed = 115200
upload_speed = 921600
extra_scripts = pre:tools/build_config_ui.py
